# Generated by Django 4.2.1 on 2023-06-11 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtechapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to=settings.AUTH_USER_MODEL),
        ),
    ]
