# Generated by Django 4.2.1 on 2023-07-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0002_alter_mydata_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='postdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'All'), (2, 'MOBILES'), (3, 'Laptops'), (4, 'Gadgets'), (5, 'New apps/websites'), (4, 'New Games'), (4, 'EV Bikes'), (4, 'EV Cars'), (4, 'TECHNews')], default=0)),
                ('thumbimg', models.ImageField(upload_to='meadia/thumbimg/')),
                ('thumbtext', models.TextField()),
                ('upload_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
