# Generated by Django 4.2.1 on 2023-07-06 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtechapp', '0003_postdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='category',
            field=models.IntegerField(choices=[(1, 'All'), (2, 'MOBILES'), (3, 'Laptops'), (4, 'Gadgets'), (5, 'New apps/websites'), (6, 'New Games'), (7, 'EV Bikes'), (8, 'EV Cars'), (9, 'TECHNews')], default=0),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='thumbimg',
            field=models.ImageField(max_length=30, upload_to='media/thumbimg/'),
        ),
        migrations.CreateModel(
            name='whislist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtechapp.postdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
