# Generated by Django 4.2.1 on 2023-07-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0005_alter_userdata_user_alter_whislist_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whislist',
            old_name='user',
            new_name='User',
        ),
    ]
