# Generated by Django 4.2.1 on 2023-07-07 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtechapp', '0006_rename_user_whislist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='thumbimg',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to='media/thumbimg/'),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='thumbtext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='upload_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='whislist',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whislist',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='dtechapp.postdata'),
        ),
        migrations.AlterField(
            model_name='whislist',
            name='upload_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(related_name='products', to='dtechapp.postdata')),
            ],
        ),
    ]
