# Generated by Django 4.2.1 on 2023-07-07 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0007_alter_postdata_thumbimg_alter_postdata_thumbtext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whislist',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dtechapp.postdata'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(related_name='product', to='dtechapp.postdata'),
        ),
    ]
