# Generated by Django 4.2.1 on 2023-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0008_alter_whislist_product_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='specifications',
            field=models.JSONField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
