# Generated by Django 4.2.1 on 2023-07-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0009_postdata_specifications_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='Availability',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='cons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='expected_cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='highlights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='lanuch_date',
            field=models.DateField(blank=True,null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='pros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='subimge1',
            field=models.ImageField(blank=True, null=True, upload_to='media/subimg'),
        ),
        migrations.AddField(
            model_name='postdata',
            name='subimge2',
            field=models.ImageField(blank=True, null=True, upload_to='media/subimg'),
        ),
        migrations.AddField(
            model_name='postdata',
            name='subimge3',
            field=models.ImageField(blank=True, null=True, upload_to='media/subimg'),
        ),
        migrations.AddField(
            model_name='postdata',
            name='subimge4',
            field=models.ImageField(blank=True, null=True, upload_to='media/subimg'),
        ),
        migrations.AddField(
            model_name='postdata',
            name='subimge5',
            field=models.ImageField(blank=True, null=True, upload_to='media/subimg'),
        ),
        migrations.AddField(
            model_name='postdata',
            name='usage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='specifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
