# Generated by Django 4.2.1 on 2023-07-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0010_postdata_availability_postdata_cons_postdata_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='lanuch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
