# Generated by Django 4.2.1 on 2023-07-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0011_alter_postdata_lanuch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='lanuch_date',
            field=models.DateField(blank=True, default=1966, null=True),
        ),
    ]
