# Generated by Django 4.2.1 on 2023-07-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0012_alter_postdata_lanuch_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbtxt', models.TextField(blank=True, null=True)),
                ('thumbimg', models.ImageField(blank=True, max_length=30, null=True, upload_to='media/thumbimg/')),
                ('subimge1', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('tech_specifications', models.JSONField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('Availability', models.JSONField(blank=True, null=True)),
                ('used_for', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
