# Generated by Django 4.2.1 on 2023-07-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0013_gadgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadgets',
            name='upload_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
