# Generated by Django 4.2.1 on 2023-07-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0014_gadgets_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps_websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbtxt', models.TextField(blank=True, null=True)),
                ('thumbimg', models.ImageField(blank=True, max_length=30, null=True, upload_to='media/thumbimg/')),
                ('logoimg', models.ImageField(blank=True, max_length=30, null=True, upload_to='media/thumbimg/')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('subimge1', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge2', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge3', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge4', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge5', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos')),
                ('features', models.JSONField(blank=True, null=True)),
                ('compatability', models.JSONField(blank=True, null=True)),
                ('user_benfits', models.JSONField(blank=True, null=True)),
                ('pricePlans', models.JSONField(blank=True, null=True)),
                ('updates', models.TextField(blank=True, null=True)),
                ('Availability', models.JSONField(blank=True, null=True)),
                ('made_in', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbtxt', models.TextField(blank=True, null=True)),
                ('thumbimg', models.ImageField(blank=True, max_length=30, null=True, upload_to='media/thumbimg/')),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos')),
                ('subimge1', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge2', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge3', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge4', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge5', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('ride_experience', models.TextField(blank=True, null=True)),
                ('battery', models.JSONField(blank=True, null=True)),
                ('Riding_modes', models.JSONField(blank=True, null=True)),
                ('design', models.JSONField(blank=True, null=True)),
                ('safety_features', models.JSONField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('warranty', models.TextField(blank=True, null=True)),
                ('chargingRange', models.JSONField(blank=True, null=True)),
                ('future_developments', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gadgets',
            name='subimge2',
            field=models.ImageField(blank=True, null=True, upload_to='media/subimg'),
        ),
        migrations.AddField(
            model_name='gadgets',
            name='subimge3',
            field=models.ImageField(blank=True, null=True, upload_to='media/subimg'),
        ),
        migrations.AddField(
            model_name='gadgets',
            name='subimge4',
            field=models.ImageField(blank=True, null=True, upload_to='media/subimg'),
        ),
        migrations.AddField(
            model_name='gadgets',
            name='subimge5',
            field=models.ImageField(blank=True, null=True, upload_to='media/subimg'),
        ),
        migrations.AddField(
            model_name='gadgets',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos'),
        ),
    ]
