# Generated by Django 4.2.1 on 2023-07-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0016_apps_websites_dislikes_apps_websites_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps_websites',
            name='category',
            field=models.IntegerField(choices=[(4, 'New apps/websites'), (0, 'none')], default=0),
        ),
        migrations.AddField(
            model_name='ev',
            name='category',
            field=models.IntegerField(choices=[(5, 'New apps/websites'), (0, 'none')], default=0),
        ),
        migrations.AddField(
            model_name='gadgets',
            name='categorys',
            field=models.IntegerField(choices=[(3, 'Gadgets'), (0, 'none')], default=0),
        ),
        migrations.AddField(
            model_name='postdata',
            name='categorys',
            field=models.IntegerField(choices=[(1, 'MOBILES'), (2, 'Laptops')], default=0),
        ),
    ]
