# Generated by Django 4.2.1 on 2023-07-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0017_apps_websites_category_ev_category_gadgets_categorys_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps_websites',
            old_name='category',
            new_name='categorys',
        ),
        migrations.RenameField(
            model_name='ev',
            old_name='category',
            new_name='categorys',
        ),
    ]
