# Generated by Django 4.2.1 on 2023-07-13 04:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtechapp', '0020_postdata_likedusers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postdata',
            unique_together={('likedUsers',)},
        ),
    ]
