# Generated by Django 4.2.1 on 2023-07-13 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtechapp', '0021_alter_postdata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='likedUsers',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likedusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
