# Generated by Django 4.2.1 on 2023-07-13 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtechapp', '0022_alter_postdata_likedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_likes',
            name='content_type',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_likes',
            name='object_id',
            field=models.PositiveIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='user_likes',
            unique_together={('User', 'content_type', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='user_likes',
            name='product',
        ),
    ]
