# Generated by Django 4.2.1 on 2023-07-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0023_user_likes_content_type_user_likes_object_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postdata',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='postdata',
            name='likedUsers',
        ),
    ]
