# Generated by Django 4.2.1 on 2023-07-13 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dtechapp', '0024_alter_postdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_likes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user_likes',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='user_likes',
            unique_together={('User', 'content_type', 'object_id', 'is_like')},
        ),
    ]
