# Generated by Django 4.2.1 on 2023-07-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0025_alter_user_likes_unique_together_user_likes_is_like_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user_likes',
            constraint=models.UniqueConstraint(fields=('content_type', 'is_like'), name='unique'),
        ),
    ]
