# Generated by Django 4.2.1 on 2023-07-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0026_user_likes_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_likes',
            name='unique',
        ),
    ]
