# Generated by Django 4.2.1 on 2023-07-15 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dtechapp', '0027_remove_user_likes_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whislist',
            name='product',
        ),
        migrations.AddField(
            model_name='whislist',
            name='added_whishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whislist',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='whislist',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
