# Generated by Django 4.2.1 on 2023-07-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0028_remove_whislist_product_whislist_added_whishlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='thumbtext',
            new_name='thumbtxt',
        ),
    ]
