# Generated by Django 4.2.1 on 2023-07-15 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtechapp', '0029_rename_thumbtext_postdata_thumbtxt'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='media/user_imgs')),
                ('comment', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
