# Generated by Django 4.2.1 on 2023-07-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dtechapp', '0030_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content_type_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comments',
            name='object_id_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
