# Generated by Django 4.2.1 on 2023-08-04 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0031_comments_content_type_c_comments_object_id_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='lanuch_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
