# Generated by Django 4.2.1 on 2023-09-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0032_alter_postdata_lanuch_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps_websites',
            old_name='features',
            new_name='App_info',
        ),
        migrations.RenameField(
            model_name='apps_websites',
            old_name='updates',
            new_name='about_app',
        ),
        migrations.RemoveField(
            model_name='apps_websites',
            name='title',
        ),
        migrations.AddField(
            model_name='apps_websites',
            name='Rating',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
