# Generated by Django 4.2.1 on 2023-09-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0033_rename_features_apps_websites_app_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps_websites',
            name='user_benfits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
