# Generated by Django 4.2.1 on 2023-09-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0034_alter_apps_websites_user_benfits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps_websites',
            name='categorys',
            field=models.IntegerField(choices=[(4, 'New apps/websites'), (6, 'Games'), (0, 'none')], default=0),
        ),
    ]
