# Generated by Django 4.2.1 on 2023-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0035_alter_apps_websites_categorys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.IntegerField(choices=[(4, 'New apps/websites'), (6, 'Games'), (0, 'none')], default=0)),
                ('thumbtxt', models.TextField(blank=True, null=True)),
                ('thumbimg', models.ImageField(blank=True, max_length=30, null=True, upload_to='media/thumbimg/')),
                ('logoimg', models.ImageField(blank=True, max_length=30, null=True, upload_to='media/thumbimg/')),
                ('subimge1', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge2', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge3', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge4', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge5', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos')),
                ('game_info', models.JSONField(blank=True, null=True)),
                ('compatability', models.JSONField(blank=True, null=True)),
                ('Rating', models.JSONField(blank=True, null=True)),
                ('pricePlans', models.JSONField(blank=True, null=True)),
                ('about_game', models.TextField(blank=True, null=True)),
                ('Availability', models.JSONField(blank=True, null=True)),
                ('made_in', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('dislikes', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
