# Generated by Django 4.2.1 on 2023-09-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0036_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVbikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.IntegerField(choices=[(5, 'EVcars'), (7, 'EVbikes')], default=0)),
                ('thumbtxt', models.TextField(blank=True, null=True)),
                ('thumbimg', models.ImageField(blank=True, max_length=30, null=True, upload_to='media/thumbimg/')),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos')),
                ('subimge1', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge2', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge3', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge4', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge5', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('ride_experience', models.TextField(blank=True, null=True)),
                ('battery', models.JSONField(blank=True, null=True)),
                ('Riding_modes', models.JSONField(blank=True, null=True)),
                ('design', models.JSONField(blank=True, null=True)),
                ('safety_features', models.JSONField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('warranty', models.TextField(blank=True, null=True)),
                ('chargingRange', models.JSONField(blank=True, null=True)),
                ('future_developments', models.JSONField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('dislikes', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EVcars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.IntegerField(choices=[(5, 'EVcars'), (7, 'Evbikes')], default=0)),
                ('thumbtxt', models.TextField(blank=True, null=True)),
                ('thumbimg', models.ImageField(blank=True, max_length=30, null=True, upload_to='media/thumbimg/')),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos')),
                ('subimge1', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge2', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge3', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge4', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('subimge5', models.ImageField(blank=True, null=True, upload_to='media/subimg')),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('ride_experience', models.TextField(blank=True, null=True)),
                ('battery', models.JSONField(blank=True, null=True)),
                ('Riding_modes', models.JSONField(blank=True, null=True)),
                ('design', models.JSONField(blank=True, null=True)),
                ('safety_features', models.JSONField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('warranty', models.TextField(blank=True, null=True)),
                ('chargingRange', models.JSONField(blank=True, null=True)),
                ('future_developments', models.JSONField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('dislikes', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ev',
        ),
    ]
