# Generated by Django 4.2.1 on 2023-09-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0037_evbikes_evcars_delete_ev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcars',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='evcars',
            name='design',
        ),
        migrations.RemoveField(
            model_name='evcars',
            name='future_developments',
        ),
        migrations.AddField(
            model_name='evcars',
            name='cons',
            field=models.JSONField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='evcars',
            name='pros',
            field=models.JSONField(blank=True, max_length=30, null=True),
        ),
    ]
