# Generated by Django 4.2.1 on 2023-09-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0038_remove_evcars_battery_remove_evcars_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcars',
            name='Rating',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
