# Generated by Django 4.2.1 on 2023-09-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0039_evcars_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evbikes',
            old_name='battery',
            new_name='Rating',
        ),
        migrations.RemoveField(
            model_name='evbikes',
            name='design',
        ),
        migrations.RemoveField(
            model_name='evbikes',
            name='future_developments',
        ),
        migrations.AddField(
            model_name='evbikes',
            name='cons',
            field=models.JSONField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='evbikes',
            name='pros',
            field=models.JSONField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='evbikes',
            name='categorys',
            field=models.IntegerField(choices=[(5, 'EVcars'), (7, 'Evbikes')], default=0),
        ),
    ]
