# Generated by Django 4.2.1 on 2023-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0040_rename_battery_evbikes_rating_remove_evbikes_design_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.IntegerField(choices=[(5, 'EVcars'), (7, 'Evbikes')], default=0)),
                ('thumbtxt', models.TextField(blank=True, null=True)),
                ('thumbimg', models.ImageField(blank=True, max_length=30, null=True, upload_to='media/thumbimg/')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos')),
                ('about_news', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('dislikes', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
