# Generated by Django 4.2.1 on 2023-09-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0041_technews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technews',
            name='categorys',
            field=models.IntegerField(choices=[(8, 'Technews'), (0, 'None')], default=0),
        ),
    ]
