# Generated by Django 4.2.1 on 2023-09-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0042_alter_technews_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='technews',
            name='main_points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technews',
            name='sample_img',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to='media/thumbimg/'),
        ),
        migrations.AddField(
            model_name='technews',
            name='sample_img_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technews',
            name='sample_video_txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
