# Generated by Django 4.2.1 on 2024-01-20 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0044_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
