# Generated by Django 4.2.1 on 2024-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0045_search_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='sort_data',
            field=models.IntegerField(null=True),
        ),
    ]
