# Generated by Django 4.2.1 on 2024-02-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtechapp', '0046_search_sort_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps_websites',
            name='brand',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apps_websites',
            name='categories_with_time',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='apps_websites',
            name='title',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='evbikes',
            name='brand',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evbikes',
            name='categories_with_time',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='evbikes',
            name='title',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='evcars',
            name='brand',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evcars',
            name='categories_with_time',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='evcars',
            name='title',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='gadgets',
            name='brand',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gadgets',
            name='categories_with_time',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='gadgets',
            name='title',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='brand',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='categories_with_time',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='title',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='brand',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='categories_with_time',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='title',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='technews',
            name='brand',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='technews',
            name='categories_with_time',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='technews',
            name='title',
            field=models.TextField(default='none', null=True),
        ),
    ]
